package e2b

import (
	"os/exec"
	"strings"
	"testing"
)

func TestGoDocSurfaceMatchesAlignedExportNames(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name     string
		pkg      string
		mustHave []string
		mustMiss []string
	}{
		{
			name: "root",
			pkg:  "github.com/e2b-dev/e2b-go-sdk",
			mustHave: []string{
				"type ConnectionConfig struct",
				"type ConnectionOpts struct",
				"type Username =",
				"type AuthenticationError =",
				"type FileNotFoundError =",
				"type GitAuthError =",
				"type GitUpstreamError =",
				"type InvalidArgumentError =",
				"type NotEnoughSpaceError =",
				"type NotFoundError =",
				"type SandboxError =",
				"type SandboxNotFoundError =",
				"type TemplateError =",
				"type TimeoutError =",
				"type RateLimitError =",
				"type BuildError =",
				"type FileUploadError =",
				"type VolumeError =",
				"type Logger =",
				"func GetSignature(",
				"type FileType =",
				"type WriteInfo =",
				"type EntryInfo =",
				"type Filesystem =",
				"type FilesystemWriteOpts =",
				"type FilesystemReadOpts =",
				"type FilesystemEventType =",
				"type FilesystemEvent =",
				"type WatchHandle =",
				"type CommandExitError =",
				"type CommandResult =",
				"type CommandHandle =",
				"type Sandbox struct",
				"type SandboxInfo struct",
				"type SandboxMetrics struct",
				"type SandboxOpts struct",
				"type SandboxApiOpts struct",
				"type SandboxConnectOpts struct",
				"type SandboxBetaCreateOpts struct",
				"type SandboxMetricsOpts struct",
				"type SandboxState string",
				"type SandboxListOpts struct",
				"type SandboxPaginator struct",
				"type SandboxNetworkOpts struct",
				"type SandboxLifecycle struct",
				"type SandboxInfoLifecycle struct",
				"type SnapshotInfo struct",
				"type SnapshotListOpts struct",
				"type SnapshotPaginator struct",
				"type McpServer map[string]any",
				"const ALL_TRAFFIC =",
				"func Create(ctx context.Context,",
				"func Connect(ctx context.Context,",
				"func List(opts *SandboxListOpts)",
				"func Kill(",
				"func GetInfo(",
				"func GetMetrics(",
				"func SetTimeout(",
				"func Pause(",
				"func BetaPause(",
				"func CreateSnapshot(",
				"func ListSnapshots(",
				"func DeleteSnapshot(",
				"type ProcessInfo =",
				"type CommandRequestOpts =",
				"type CommandConnectOpts =",
				"type CommandStartOpts =",
				"type Commands =",
				"type Pty =",
				"type Git =",
				"type GitRequestOpts =",
				"type GitCloneOpts =",
				"type GitInitOpts =",
				"type GitRemoteAddOpts =",
				"type GitCommitOpts =",
				"type GitAddOpts =",
				"type GitDeleteBranchOpts =",
				"type GitPushOpts =",
				"type GitPullOpts =",
				"type GitDangerouslyAuthenticateOpts =",
				"type GitConfigOpts =",
				"type GitConfigScope =",
				"type GitBranches =",
				"type GitFileStatus =",
				"type GitStatus =",
				"type Volume =",
				"type VolumeFileType =",
				"type VolumeInfo =",
				"type VolumeAndToken =",
				"type VolumeEntryStat =",
				"type VolumeMetadataOptions =",
				"type VolumeWriteOptions =",
				"type TemplateFromImage =",
				"type TemplateBuilder =",
				"type TemplateFinal =",
				"type TemplateClass =",
				"type McpServerName =",
				"func Exists(",
				"func Build(",
				"func BuildInBackground(",
				"func ToJSON(",
				"func ToDockerfile(",
				"func AssignTags(",
				"func RemoveTags(",
				"func GetBuildStatus(",
				"func GetTags(",
				"func WaitForPort(",
				"func WaitForURL(",
				"func WaitForProcess(",
				"func WaitForFile(",
				"func WaitForTimeout(",
				"func NewLogEntryStart(",
				"func NewLogEntryEnd(",
				"func DefaultBuildLogger(",
				"type ApiClient =",
				"type VolumeApiOpts =",
				"type Stdout =",
				"type Stderr =",
				"type PtyOutput =",
			},
			mustMiss: []string{
				"func TemplateExists(",
				"type ApiClientOpts ",
				"type CopyOpts =",
				"type RemoveOpts =",
				"type RunCmdOpts =",
				"type InstallOpts =",
				"func CreateSandbox(",
				"func ConnectSandbox(",
				"func ListSandboxes(",
				"func KillSandbox(",
				"func GetSandboxInfo(",
				"func GetSandboxMetrics(",
				"func SetSandboxTimeout(",
				"func PauseSandbox(",
				"func BetaPauseSandbox(",
			},
		},
		{
			name: "template",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/template",
			mustHave: []string{
				"func GetBuildStatus(",
				"func ToJSON(",
				"func ToDockerfile(",
				"type TemplateFromImage interface",
				"type TemplateBuilder interface",
				"type TemplateFinal interface",
				"type TemplateClass interface",
				"type McpServerName =",
				"func AssignTags(",
				"func RemoveTags(",
				"func Template(",
			},
			mustMiss: []string{
				"func GetBuildStatusByData(",
				"func AssignTemplateTags(",
				"func RemoveTemplateTags(",
				"func NewTemplate(",
				"type CopyOpts struct",
				"type RemoveOpts struct",
				"type RunCmdOpts struct",
				"type InstallOpts struct",
			},
		},
		{
			name: "template-type",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/template.TemplateBase",
			mustHave: []string{
				"type TemplateBase struct",
				"func (t *TemplateBase) Copy(",
				"func (t *TemplateBase) AddMcpServer(",
				"func (t *TemplateBase) BetaDevContainerPrebuild(",
				"func (t *TemplateBase) BetaSetDevContainerStart(",
				"func (t *TemplateBase) RunCmd(",
				"func (t *TemplateBase) SetEnvs(",
				"func (t *TemplateBase) SetStartCmd(",
			},
			mustMiss: []string{
				"func (t *TemplateBase) GetInstructions(",
			},
		},
		{
			name: "volume",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/volume",
			mustHave: []string{
				"type ConnectionOpts struct",
				"func GetInfo(",
			},
			mustMiss: []string{
				"type VolumeOpts =",
				"func GetVolumeInfo(",
				"const FileTimeoutMs",
			},
		},
		{
			name: "commands",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/commands",
			mustHave: []string{
				"type Commands struct",
				"func NewCommands(",
				"type Pty struct",
				"func NewPty(",
				"type CommandRequestOpts struct",
				"type CommandStartOpts struct",
				"type CommandConnectOpts struct",
				"type ProcessInfo struct",
				"type Stdout =",
				"type Stderr =",
				"type PtyOutput =",
			},
			mustMiss: []string{
				"type ConnectionConfig struct",
			},
		},
		{
			name: "commands-handle",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/commands.CommandHandle",
			mustHave: []string{
				"type CommandHandle struct",
				"func (h *CommandHandle) Disconnect()",
				"func (h *CommandHandle) Kill()",
				"func (h *CommandHandle) Wait()",
				"func (h *CommandHandle) GetStdout()",
				"func (h *CommandHandle) GetStderr()",
				"func (h *CommandHandle) GetExitCode()",
				"func (h *CommandHandle) GetError()",
			},
			mustMiss: []string{
				"func NewCommandHandle(",
				"func (h *CommandHandle) AppendStdout(",
				"func (h *CommandHandle) AppendStderr(",
				"func (h *CommandHandle) SetEnd(",
				"func (h *CommandHandle) SetWaitError(",
			},
		},
		{
			name: "commands-type",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/commands.Commands",
			mustHave: []string{
				"type Commands struct",
				"func (c *Commands) Connect(",
				"func (c *Commands) Kill(",
				"func (c *Commands) List(",
				"func (c *Commands) Run(",
				"func (c *Commands) RunBackground(",
				"func (c *Commands) SendStdin(",
			},
			mustMiss: []string{
				"func (c *Commands) CloseStdin(",
			},
		},
		{
			name: "filesystem",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/filesystem",
			mustHave: []string{
				"type Filesystem struct",
				"func NewFilesystem(",
				"type EntryInfo struct",
				"type FileType string",
				"type FilesystemReadOpts struct",
				"type FilesystemWriteOpts struct",
				"type FilesystemEvent struct",
				"type WatchHandle struct",
			},
			mustMiss: []string{
				"type ConnectionConfig struct",
				"func NewWatchHandle(",
				"type FileNotFoundError struct",
			},
		},
		{
			name: "volume-type",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/volume.Volume",
			mustHave: []string{
				"type Volume struct",
				"VolumeID string",
				"Name     string",
				"Token    string",
				"Domain   string",
				"Debug    bool",
				"func (v *Volume) Exists(",
				"func (v *Volume) GetInfo(",
				"func (v *Volume) List(",
				"func (v *Volume) MakeDir(",
				"func (v *Volume) ReadFile(",
				"func (v *Volume) ReadFileText(",
				"func (v *Volume) Remove(",
				"func (v *Volume) UpdateMetadata(",
				"func (v *Volume) WriteFile(",
			},
			mustMiss: []string{
				"func (v *Volume) ListDir(",
			},
		},
		{
			name: "git",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/git",
			mustHave: []string{
				"type Git struct",
				"func NewGit(",
				"type GitRequestOpts struct",
				"type GitCloneOpts struct",
				"type GitInitOpts struct",
				"type GitRemoteAddOpts struct",
				"type GitCommitOpts struct",
				"type GitAddOpts struct",
				"type GitResetMode string",
				"type GitResetOpts struct",
				"type GitRestoreOpts struct",
				"type GitDeleteBranchOpts struct",
				"type GitPushOpts struct",
				"type GitPullOpts struct",
				"type GitConfigOpts struct",
				"type GitDangerouslyAuthenticateOpts struct",
				"type GitConfigScope string",
				"type GitBranches struct",
				"type GitFileStatus struct",
				"type GitStatus struct",
			},
			mustMiss: []string{
				"func BuildGitCommand(",
				"func DeriveRepoDirFromUrl(",
				"func GetRepoPathForScope(",
				"func GetScopeFlag(",
				"func IsAuthFailure(",
				"func IsMissingUpstream(",
				"func ParseGitBranches(",
				"func ParseGitStatus(",
				"func ShellEscape(",
				"func StripCredentials(",
				"func WithCredentials(",
				"type GitAuthError struct",
				"type GitStatusLabel string",
				"type GitUpstreamError struct",
			},
		},
		{
			name: "git-type",
			pkg:  "github.com/e2b-dev/e2b-go-sdk/git.Git",
			mustHave: []string{
				"type Git struct",
				"func (g *Git) Add(",
				"func (g *Git) Branches(",
				"func (g *Git) CheckoutBranch(",
				"func (g *Git) Clone(",
				"func (g *Git) Commit(",
				"func (g *Git) ConfigureUser(",
				"func (g *Git) CreateBranch(",
				"func (g *Git) DangerouslyAuthenticate(",
				"func (g *Git) DeleteBranch(",
				"func (g *Git) GetConfig(",
				"func (g *Git) Init(",
				"func (g *Git) Pull(",
				"func (g *Git) Push(",
				"func (g *Git) RemoteAdd(",
				"func (g *Git) RemoteGet(",
				"func (g *Git) Reset(",
				"func (g *Git) Restore(",
				"func (g *Git) SetConfig(",
				"func (g *Git) Status(",
			},
		},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			cmd := exec.Command("go", "doc", tc.pkg)
			cmd.Dir = "."
			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("go doc %s failed: %v\n%s", tc.pkg, err, string(out))
			}

			doc := string(out)
			for _, want := range tc.mustHave {
				if !strings.Contains(doc, want) {
					t.Fatalf("expected go doc for %s to contain %q\n%s", tc.pkg, want, doc)
				}
			}
			for _, unwanted := range tc.mustMiss {
				if strings.Contains(doc, unwanted) {
					t.Fatalf("expected go doc for %s to omit %q\n%s", tc.pkg, unwanted, doc)
				}
			}
		})
	}
}
